### ISSUE TITLE
"TypeError: undefined is not a function" if no default account store

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-node-config#11]
Stacktrace:

```
TypeError: undefined is not a function
    at /Users/robert/projects/express-stormpath/node_modules/stormpath-config/lib/strategy/EnrichIntegrationFromRemoteConfigStrategy.js:149:9
    at Object.wrapGetResourceResponse [as _wrapGetResourceResponse] (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:67:12)
    at onGetResourceRequestResult (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/DataStore.js:278:13)
    at Request.onRequestResult [as _callback] (/Users/robert/projects/express-stormpath/node_modules/stormpath/lib/ds/RequestExecutor.js:100:14)
    at Request.self.callback (/Users/robert/projects/express-stormpath/node_modules/request/request.js:198:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/Users/robert/projects/express-stormpath/node_modules/request/request.js:1035:10)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/Users/robert/projects/express-stormpath/node_modules/request/request.js:962:12)
    at IncomingMessage.emit (events.js:129:20)
```

This happens when there is no default account store mapped to the specified application.  This strategy should be modified to support the following situations:

* If the application has 0 account stores mapped to it, we should provide the error "No account stores are mapped to the specified application.  Account stores are required for login and registration"

* If there is no default account store for the application, then:
 * If `stormpath.web.register.enabled` is `true`, then we should provide the error "No default account store is mapped to the specified application.  A default account store is required for registration." 

 * If `stormpath.web.register.enabled` is `false`, then we should not error.  We should allow configuration parsing to continue, and the integration should be allowed to initialize.  This is necessary because some applications provide login but not registration.

**Comment by typerandom** [comment]
I think this issue has already been fixed here #10. I will review @timothyej's changes and merge it in.

**Comment by robertjd** [comment]
Thanks @typerandom , please ensure that the merged code has the friendly messages that are defined above.

**Comment by typerandom** [comment]
Closing issue since PR merged.
