### ISSUE TITLE
method are removed from cacheOptions.client 

### ISSUE THREAD

**Issue by robertjd** [stormpath/stormpath-node-config#12]
If you attempt to supply a cache client instance, like this:

```
var stormpath = require('stormpath');
var redis = require('redis');

var rc = redis.createClient();

var client = new stormpath.Client({
  cacheOptions: {
    store: 'redis',
    client: rc
  }
});
```

You will get this error:

```
/Users/robert/projects/nodeapp/node_modules/stormpath/lib/cache/RedisStore.js:26
  this.redis.get(key, function(err, entry){
             ^
TypeError: undefined is not a function
    at RedisStore.get (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/cache/RedisStore.js:26:14)
    at Cache.get (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/cache/Cache.js:52:14)
    at CacheHandler.getCachedResource [as get] (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/cache/CacheHandler.js:91:51)
    at Object.executeRequest [as exec] (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/ds/DataStore.js:294:22)
    at DataStore.getResource (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/ds/DataStore.js:122:16)
    at Client.getResource (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/Client.js:185:38)
    at Client.getApplication (/Users/robert/projects/nodeapp/node_modules/stormpath/lib/Client.js:514:15)
    at EnrichClientFromRemoteConfigStrategy._resolveApplicationByHref (/Users/robert/projects/nodeapp/node_modules/stormpath/node_modules/stormpath-config/lib/strategy/EnrichClientFromRemoteConfigStrategy.js:16:10)
    at Client.<anonymous> (/Users/robert/projects/nodeapp/node_modules/stormpath/node_modules/stormpath-config/lib/strategy/EnrichClientFromRemoteConfigStrategy.js:68:9)
    at Client.emit (events.js:107:17)
```

It seems that our object extension algorithm is stripping properties that are functions.

This problem happens during this extension:

https://github.com/stormpath/stormpath-node-config/blob/master/lib/strategy/ExtendConfigStrategy.js#L15

A quick fix would be this block of code, added after that extension:

```
if(this.extendWith.cacheOptions && this.extendWith.cacheOptions.client){
  config.cacheOptions.client = this.extendWith.cacheOptions.client;
}
```

@typerandom thoughts?

**Comment by typerandom** [comment]
@robertjd I don't like hacks like this. But we can definitely do that one now and then look for a better solution (i.e. likely using another extension method).

**Comment by typerandom** [comment]
Closing issue since PR with hack is merged.
